name: comb
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=py313h06a4308_0
  - aiohappyeyeballs=2.4.4=py313h06a4308_0
  - aiohttp=3.11.10=py313h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=19.0.0=hfcf91c8_3
  - attrs=24.3.0=py313h06a4308_0
  - aws-c-auth=0.8.5=h5eee18b_0
  - aws-c-cal=0.8.5=hdbd6064_0
  - aws-c-common=0.11.1=h5eee18b_0
  - aws-c-compression=0.3.1=h5eee18b_0
  - aws-c-event-stream=0.5.4=h6a678d5_0
  - aws-c-http=0.9.3=h5eee18b_0
  - aws-c-io=0.17.0=h5eee18b_0
  - aws-c-mqtt=0.12.2=h5eee18b_0
  - aws-c-s3=0.7.11=hdbd6064_0
  - aws-c-sdkutils=0.2.3=h5eee18b_0
  - aws-checksums=0.2.3=h5eee18b_0
  - aws-crt-cpp=0.31.0=h6a678d5_0
  - aws-sdk-cpp=1.11.528=h74f24ce_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py313hf0014fa_0
  - brotli-python=1.0.9=py313h6a678d5_9
  - brotlicffi=1.0.9.2=py313h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cachetools=5.5.1=py313h06a4308_0
  - certifi=2025.6.15=py313h06a4308_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py313h06a4308_0
  - contourpy=1.3.1=py313hdb19cb5_0
  - cryptography=44.0.1=py313h7825ff9_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dill=0.3.8=py313h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - filelock=3.17.0=py313h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py313h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.5.0=py313h5eee18b_0
  - fsspec=2024.12.0=py313h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - google-auth=2.38.0=py313h06a4308_1
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.71.0=py313h6a678d5_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.8=py313h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.8=py313h06a4308_0
  - markupsafe=3.0.2=py313h5eee18b_0
  - matplotlib=3.10.0=py313h06a4308_1
  - matplotlib-base=3.10.0=py313h68cf311_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py313h5eee18b_2
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - multidict=6.1.0=py313h5eee18b_0
  - multiprocess=0.70.15=py313h06a4308_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.10.1=py313h3c60e43_0
  - oauthlib=3.3.1=py313h06a4308_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.16=h5eee18b_0
  - orc=2.1.1=hd396ef6_0
  - packaging=24.2=py313h06a4308_0
  - pandas=2.2.3=py313h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - pip=25.1=pyhc872135_2
  - propcache=0.3.1=py313h5eee18b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=19.0.0=py313h6a678d5_1
  - pyasn1=0.6.1=py313h06a4308_0
  - pyasn1-modules=0.4.2=py313h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=25.0.0=py313h06a4308_0
  - pyparsing=3.2.0=py313h06a4308_0
  - pyqt=6.7.1=py313h6a678d5_1
  - pyqt6-sip=13.9.1=py313h5eee18b_1
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.5=h4612cfd_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py313h5eee18b_0
  - python_abi=3.13=0_cp313
  - pytz=2025.2=py313h06a4308_0
  - pyyaml=6.0.2=py313h5eee18b_0
  - qtbase=6.7.3=hdaa5aa8_0
  - qtdeclarative=6.7.3=h6a678d5_0
  - qtsvg=6.7.3=he621ea3_0
  - qttools=6.7.3=h80c7b02_0
  - qtwebchannel=6.7.3=h6a678d5_0
  - qtwebsockets=6.7.3=h6a678d5_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - regex=2024.11.6=py313h5eee18b_0
  - requests=2.32.4=py313h06a4308_0
  - requests-oauthlib=2.0.0=py313h06a4308_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - s2n=1.5.14=hdbd6064_0
  - safetensors=0.5.3=py313h8a85203_0
  - sip=6.10.0=py313h6a678d5_0
  - six=1.17.0=py313h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tk=8.6.14=h993c535_1
  - tornado=6.5.1=py313h5eee18b_0
  - tqdm=4.67.1=py313h7040dfc_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py313h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - werkzeug=3.1.3=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py313h5eee18b_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - addict==2.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - anyio==4.10.0
      - apache-tvm-ffi==0.1.6
      - astor==0.8.1
      - blake3==1.0.5
      - cbor2==5.6.5
      - cloudpickle==3.1.1
      - compressed-tensors==0.12.2
      - cuda-bindings==13.1.1
      - cuda-pathfinder==1.3.3
      - cuda-python==13.1.1
      - cupy-cuda12x==13.5.1
      - datasets==3.6.0
      - deepspeed==0.17.2
      - depyf==0.20.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - docopt==0.6.2
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.2.0
      - fastapi==0.125.0
      - fastapi-cli==0.0.8
      - fastapi-cloud-cli==0.1.5
      - fastrlock==0.8.3
      - flashinfer-python==0.5.3
      - gguf==0.17.1
      - h11==0.16.0
      - hf-xet==1.1.7
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.10.0
      - jmespath==1.0.1
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - lark==1.2.2
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mistral-common==1.8.6
      - model-hosting-container-standards==0.1.12
      - modelscope==1.28.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - networkx==3.3
      - ninja==1.11.1.4
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.16.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.3.3
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.13.0
      - openai-harmony==0.0.8
      - opencv-python-headless==4.12.0.88
      - outlines-core==0.2.11
      - partial-json-parser==0.2.1.1.post6
      - pillow==11.3.0
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - protobuf==3.20.0
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pybase64==1.4.2
      - pycountry==24.6.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.5
      - pygments==2.19.2
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pyzmq==27.0.1
      - ray==2.48.0
      - referencing==0.36.2
      - rich==14.1.0
      - rich-toolkit==0.14.9
      - rignore==0.6.4
      - rouge==1.0.1
      - rpds-py==0.27.0
      - scipy==1.16.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.34.1
      - setproctitle==1.3.7
      - setuptools==79.0.1
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - starlette==0.50.0
      - supervisor==4.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tiktoken==0.11.0
      - tokenizers==0.22.1
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - transformers==4.57.3
      - triton==3.5.0
      - typer==0.16.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - vllm==0.12.0
      - watchfiles==1.1.0
      - websockets==15.0.1
      - xformers==0.0.31
      - xgrammar==0.1.27
      - yarg==0.1.10
